import datetime


from time import gmtime,strftime

fmt = "%Y-%m-%d %H:%M:%S"


def pop_string(data,length):
    popped = data[:length]
    data = data[length:]
    return popped

def parse_string(data,length,content):

    result=pop_string(data,length)
    val = int(str(result), 16)
    #print("{} is {}".format(content,val))
    data = data[length:]

    ret = (data,val)
    return ret

def convert_to_driverid(value):
    driverid=hex(int(value))
    return(str(driverid)[3:-2][::-1].upper())


def teltonika(data):
    print("in parsed data")

    parsed=process_data(data)
    print(parsed)
    return parsed


def process_data(data):

    print("In process data")
    paramdict = {1:"DigitalInputStatus1",2:"DigitalInputStatus2",3:"DigitalInputStatus3",4:"DigitalInputStatus4",9:"AnalogInput1",10:"AnalogInput2",21:"GSMlevel",24:"Speed",66:"ExternalPowerVoltage",67:"BatteryVoltage",68:"BatteryCurrent",69:"GNSSStatus",72:"DallasTemperature1",73:"DallasTemperature2",74:"DallasTemperature3",75:"DallasTemperatureSensorID1",76:"DallasTemperatureSensorID2",77:"DallasTemperatureSensorID3",78:"iButtonID",79:"Networktype",80:"WorkingMode",99:"Continuousodometer",179:"DigitalOutput1state",180:"DigitalOutput2state",181:"PDOP",182:"HDOP",199:"OdometerValue(VirtualOdometer)",200:"DeepSleep",205:"CellID",206:"AreaCode",239:"Ignition",240:"MovementSensor",241:"GSMOperatorCode",155:"Geofence zone 01",156:"Geofence zone 02",157:"Geofence zone 03",158:"Geofence zone 04",159:"Geofence zone 05",175:"Auto Geofence",177:"Idling",249:"Jamming detection",250:"Trip",251:"Immobilizer",252:"Authorized driving",253:"Green driving type",254:"Green driving value",255:"Over Speeding"}

    #additional for FM63
    paramdict.update({219:"(MSB)CCID",220:"CCID",221:"(LSB)CCID",62:"DallasTemperatureID1",63:"DallasTemperatureID2",64:"DallasTemperatureID3",65:"DallasTemperatureID4",216:"TotalOdometer",218:"IMSI",22:"ActualProfile",71:"GNSSStatus",178:"NetworkType",236:"X-axis",237:"Y-axis",238:"Z-axis"})

    if (len(data)>34):
        parsed=[]
        print ("{} received data:  {}".format(strftime("%Y-%m-%d %H:%M:%S", gmtime()),data))
        print((len(data)/2))

        # drop first 16 chars (8 bytes)
        #result=pop_string(data,16)
        #print(result)
        #data = data[16:]

        #codec
        result=pop_string(data,2)
        line=("Codec is {}".format(int(result, 16)))
        parsed.append(line)
        data = data[2:]

        #avl data count
        count=pop_string(data,2)
        line=("AVL data count is {}".format(int(count, 16)))
        parsed.append(line)
        data = data[2:]

        for i in range(0,int(count, 16)):

            # timestamp
            result=pop_string(data,16)
            epochtime =int(result, 16)

            t = datetime.datetime.fromtimestamp(float(epochtime)/1000.)
            line=("Epoch is {} Timestampt is  {}".format(epochtime,t.strftime(fmt))) # prints 2012-08-28 02:45:17
            parsed.append(line)
            data = data[16:]

            result=pop_string(data,2)
            line=("Priority is {}".format(int(result, 16)))
            parsed.append(line)
            data = data[2:]

            result=pop_string(data,30)
            line=("GPS is {}".format(int(result, 30)))
            parsed.append(line)
            data = data[30:]

            data,value=parse_string(data,2,"Event ID")
            line=( "The event id {} was generated by {}".format(value,paramdict.get(value)))
            parsed.append(line)


            data,value=parse_string(data,2,"Element Count")
            line=("Element Count is {}".format(value))
            parsed.append(line)


            data,value=parse_string(data,2,"1Byte element count")
            line=( " Total 1 byte elements are {}".format(value))
            parsed.append(line)
            for i in range(1,value+1):
                data,value1=parse_string(data,2,"ID")
                data,value=parse_string(data,2,"value")
                if value1 in paramdict:
                    line=( " the {} id is {}/{} with value {}".format(i,value1,paramdict.get(value1),value))
                    parsed.append(line)
                else:
                    line=( " the {} id is {} with value {}".format(i,value1,value))
                    parsed.append(line)

            data,value=parse_string(data,2,"2Byte element count")
            line=( " Total 2 byte elements are {}".format(value))
            parsed.append(line)
            for i in range(1,value+1):
                data,value1=parse_string(data,2,"ID")
                data,value=parse_string(data,4,"value")
                if value1 in paramdict:
                    line=( " the {} id is {}/{} with value {}".format(i,value1,paramdict.get(value1),value))
                    parsed.append(line)
                else:
                    line=( " the {} id is {} with value {}".format(i,value1,value))
                    parsed.append(line)

            data,value=parse_string(data,2,"4Byte element count")
            line=( " Total 4 byte elements are {}".format(value))
            parsed.append(line)
            for i in range(1,value+1):
                data,value1=parse_string(data,2,"ID")
                data,value=parse_string(data,8,"value")
                if value1 in paramdict:
                    line=( " the {} id is {}/{} with value {}".format(i,value1,paramdict.get(value1),value))
                    parsed.append(line)
                else:
                    line=( " the {} id is {} with value {}".format(i,value1,value))
                    parsed.append(line)

            data,value=parse_string(data,2,"8Byte element count")
            line=( " Total 4 byte elements are {}".format(value))
            parsed.append(line)
            for i in range(1,value+1):
                data,value1=parse_string(data,2,"ID")
                data,value=parse_string(data,16,"value")
                if value1 in paramdict:
                    if value1==78:
                        driverid=convert_to_driverid(value)
                        line=( " the {} id is {}/{} with value {}".format(i,value1,paramdict.get(value1),driverid))
                        parsed.append(line)

                    else:
                        line=( " the {} id is {}/{} with value {}".format(i,value1,paramdict.get(value1),value))
                        parsed.append(line)
                else:
                     line=( " the {} id is {} with value {}".format(i,value1,value))
                     parsed.append(line)

        data,value=parse_string(data,2,"AVL Data count")
        line=( " AVL Data count {}".format(value))
        parsed.append(line)

        #data,value=parse_string(data,8,"CRC ")
        #print( " CRC {}".format(value))

        return parsed


    else:
        return 0

if __name__ == '__main__':
    # print_a() is only executed when the module is run directly.
    teltonika("0801000000F9CEBAFA6801000000000000000000000000000000F00D08EF00F00115004502010002000300B40005B60000180000430000090088060083000001")
